version: "3.8"
services:
        work_space:
                build:
                        context: $BUILD_CONTEXT
                        dockerfile: $DOCKERFILE_PATH/Dockerfile
                        args:
                                - NAME=$NAME
                                  #- CONFIG=$CONFIG
                                - PUB=$PUB
                                - HOST=$HOST
                                - PORT_JUP=$PORT_JUP
                                - PROJECT_PATH=$PROJECT_PATH
                                - HOST_NAME=$USER
                                - HOST_IP=$HOST_IP   #$(hostname -I | awk '{print $1;}')
                image: $IMAGE
                container_name: $CONTAINER
                ports:
                        - "${PORT}:22"
                        - "${PORT_JUP}:${PORT_JUP}"  
                tty: true
                stdin_open: true 
                volumes:
                        - ${STORAGE}:${SHARA_DOC}
