version: "3.8"
services:
        work_space:
                build:
                        context: $BUILD_CONTEXT
                        dockerfile: $DOCKERFILE_PATH/Dockerfile
                        args:
                                - NAME=$NAME
                                - PUB=$PUB
                                - PORT_JUP=$PORT_JUP
                                - PROJECT_PATH=$PROJECT_PATH
                                  #- TEMPLATE_PATH=$TEMPLATE_PATH
                #env_file: config/config.env
                image: $IMAGE
                container_name: $CONTAINER
                ports:
                        - "${PORT}:22"
                        - "${PORT_JUP}:${PORT_JUP}"  
                tty: true
                stdin_open: true 
                volumes:
                        - ${STORAGE}:${SHARA_DOC}
