version: "3.8"
services:
    basic_work_space:
        build:
            context: .
            dockerfile: ./Dockerfile_basic
            args:
                - USERNAME=$USERNAME
        image: $BASE_IMAGE
    work_space:
        build:
            context: .
            dockerfile: ./Dockerfile
            args:
                - USERNAME=$USERNAME
                - BASE_IMAGE=$BASE_IMAGE
                #- JUP_PORT=$JUP_PORT
                - DOCKER_CLI_VERSION=$DOCKER_CLI_VERSION
                - DOCKER_COMPOSE_CLI_VERSION=$DOCKER_COMPOSE_CLI_VERSION
        environment:
            - JUP_PORT=$JUP_PORT
            - HOST_WORKSPACE=$HOST_WORKSPACE
            - WORKSPACE=$WORKSPACE
        image: $IMAGE
        container_name: $CONTAINER
        ports:
            - "${SSH_PORT}:22"
            - "${JUP_PORT}:${JUP_PORT}"
            - "${PORTS}:${PORTS}"
        depends_on:
            - basic_work_space
        runtime: nvidia
        shm_size: 24gb
        tty: true
        stdin_open: true 
        volumes:
                - ${HOST_WORKSPACE}:/home/${USERNAME}/workspace
                - ${HOST_STORAGE}:${STORAGE}
                - ${DOCKER_SOCK}:/var/run/docker.sock
