version: "3.8"
services:
        work_space:
                build:
                        context: $BUILD_CONTEXT
                        dockerfile: $DOCKERFILE_PATH/Dockerfile
                        args:
                                - NAME=$NAME
                                - CONFIG=$CONFIG
                                  #- PROJECT_PATH=$PROJECT_PATH
                                  #- TEMPLATE_PATH=$TEMPLATE_PATH
                image: $IMAGE
                container_name: $CONTAINER
                tty: true
                stdin_open: true 
                volumes:
                        - ${PWD}:/root
