#FROM nvcr.io/nvidia/cuda:11.3.1-devel-ubuntu20.04
FROM nvcr.io/nvidia/cuda:11.3.1-cudnn8-runtime-ubuntu20.04
#FROM nvcr.io/nvidia/pytorch:21.06-py3

ENV TZ=Europe/Moscow
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update --fix-missing && \
    apt-get upgrade -y && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        python3-pip \
        python3-dev \
        #python3.9-dev \
        vim-gtk \
        ssh \
        sudo \
        openssh-server \
        make \
        curl \
        sudo

#RUN add-apt-repository -y ppa:deadsnakes/ppa && \
#    apt-get install -y python3.9 && \
#    ln -sf /usr/bin/python3.9 /bin/python3

RUN pip3 install --upgrade pip

#Add user
ARG USERNAME
ENV WORKSPACE /home/$USERNAME
RUN useradd -rm -s /bin/bash -G sudo -u 1000 $USERNAME
RUN echo "$USERNAME:$USERNAME" | chpasswd
RUN usermod -d $WORKSPACE $USERNAME
RUN mkdir $WORKSPACE/.local
RUN mkdir $WORKSPACE/.config
RUN chown -R $USERNAME:$USERNAME $WORKSPACE

#copy my config files and utils
COPY ./utils /resources
COPY ./config /resources/config
COPY ./keys /resources/keys

#added my utils to users
RUN echo PATH="/resources:/home/$USERNAME/.local/bin:$PATH" > /etc/environment

#SSH
RUN /resources/config_ssh.sh

#CUDA
RUN add-apt-repository ppa:graphics-drivers && \
    apt-key adv --fetch-keys  http://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub && \
    apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y cuda-11-3 && \
    export PATH=/usr/local/cuda-11.3/bin:$PATH && \
    export LD_LIBRARY_PATH=/usr/local/cuda-11.0/lib64:$LD_LIBRARY_PATH

WORKDIR /resources
RUN tar -xzvf cudnn-11.3-linux-x64-v8.2.1.32.tgz && \
    cp cuda/include/cudnn*.h /usr/local/cuda/include && \
    cp cuda/lib64/libcudnn* /usr/local/cuda/lib64 && \
    chmod a+r /usr/local/cuda/include/cudnn*.h /usr/local/cuda/lib64/libcudnn*

EXPOSE 22
