#!/usr/bin/python3
import os
import sys
from switch_mount import sudstitution_argv as sv

if __name__ == '__main__':
    args = sv(sys.argv)
    args[0] = '/usr/bin/docker'
    os.system(' '.join(args))
