#!/bin/python3
import os
import sys
import subprocess
from switch_mount import substitution_file as sf

if __name__ == '__main__':
    tmp_path = None
    try:
        idx = sys.argv.index('-f') + 1
    except Exception:
        pass
    else:
        tmp_path = sys.argv[idx] + '.tmp'
        sf(sys.argv[idx], new_path=tmp_path)
        sys.argv[idx] = tmp_path
    sys.argv[0] = '/usr/bin/docker-compose'
    os.system(' '.join(sys.argv))
    if tmp_path: os.remove(tmp_path)
